[stimulation.screen]
id = 1
resolution = [1920, 1080]
background_color = [ 0, 0, 0,]
refresh_rate_hz = 60
full_screen = false

[stimulaton.timing]
flash_duration = 50
interval = 500

[speller.stt]
enabled = false
width_dva = 2.2
height_dva = 2.2
colors = [ "black", "white",]


[stimulation.controls]
continue = [ "c",]
quit = [ "q", "escape",]

[stimulation.methods]
method = "VEP"

[streams]
marker_stream_name = 'stimulation-stream'
decoder_stream_name = 'decoder-stream'
start_eval_marker = 'stimulation_start'
stim_marker = 'stimulation_presented'
